# version: "3"

# services:

#   backend:

#     build: backend/
#     command: ./social-network
#     ports:
#       - 8081:8081

#   frontend:

#     build: frontend/ 
#     command: [ "http-server", "dist" ]
#     ports:
#       - 8080:8080
#     depends_on:
#       - backend
version: '3'
services:
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      -  8080:8080  # Map the container's port 8080 to the host's port 8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      -  8001:8001  # Map the container's port 8000 to the host's port 8000